title: Ethical Data-Centric Design of Intelligent Behaviour
logo: /assets/img/logo.png
description: Workshop of Mobile HCI 2020, Oct. 5th
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
